sudo: required
language: node_js
addons:
  apt:
    packages:
      - "python"
      - "python-pip"
node_js:
  - "6"
python:
  - 2.7
before_install:
  - sudo pip install flask
  - sudo pip install requests
  - npm install -g @angular/cli
  - cd movies-app/
  - npm install
script:
  - npm run build
